### ISSUE TITLE
Issues with Using this Service 

### ISSUE THREAD

**Issue by xXYo-NachoXx** [Groopit/ra-data-odata-server#1]
Hi ! 

I am an student working for a project, and I saw this Odata Data provider, which looks great for my project where I'm implementing Odata nonetheless I have I quick question becuase is not working with my API 

First I will add the Metadata file 

![image](https://user-images.githubusercontent.com/37778175/118177933-9481f580-b3f0-11eb-8890-d6abaa8205b6.png)

I dont know if the Entity Structure is ok

Appreciate your help! 

Looking into the Issue I am getting stuck here 

![image](https://user-images.githubusercontent.com/37778175/118178200-e7f44380-b3f0-11eb-9545-c60a8fd77b96.png)

And the console is generating this error 

![image](https://user-images.githubusercontent.com/37778175/118178488-3b669180-b3f1-11eb-9404-1dccef024ba1.png)

**Comment by xXYo-NachoXx** [comment]
Another quick question is this something that We can implement in pure React without Typescript?

**Comment by jvert** [comment]
Can you add the actual metadata XML text rather than a picture of it?
