### ISSUE TITLE
Include possibility for specifying fetch-proxy

### ISSUE THREAD

**Issue by gebsl** [Groopit/ra-data-odata-server#11]
Hello,

first of all thanks for the great work that has already been done on this project!

For a custom implementation of an authentication layer I need all requests to send a cookie to the server. @odata/client provides an API to change fetch-requests on the fly. Would you mind having the functionality in this library as well?

My idea: User provides a fetch-proxy object, passes it to ra-data-odata-server and the library passes it further to @odata/client. More generic we could include an object to specify arbitrary parameters that are passed to the constructor of @odata/client, which would even allow for more customizations of the odata client.

If that sounds like a feasible idea let me know and I can submit a pull request.

Best regards,
gebsl

**Comment by jvert** [comment]
I think this is a similar issue as #10 

I tried to implement the proxy approach at one point but fell afoul of the type mismatch hell between node-fetch (used by @odata/client) and the browser DOM fetch and eventually gave up trying to reconcile the two. 

Happy to take a look at any PR though.

**Comment by gebsl** [comment]
Further discussion at https://github.com/Groopit/ra-data-odata-server/pull/13 :-)

**Comment by jvert** [comment]
fixed with #13
