### ISSUE TITLE
String to number conversion not working for Edm.Int64

### ISSUE THREAD

**Issue by gebsl** [Groopit/ra-data-odata-server#12]
Hello,

I have a database with long integers as Identifiers, which is represented as "Edm.Int64" in OData. However, the conversion of string identifiers to numbers is not working. Supposedly this is due to the following if-check that only covers "Edm.Int32":
https://github.com/Groopit/ra-data-odata-server/blob/bb8b359a73b830791b36e101cc67c44cff61586a/src/index.ts#L77

Can we change this to something like:

```javascript
else if (type.startsWith("Edm.Int") && typeof id !== "number") {
    return parseInt(id);
}
```
or

```javascript
else if (type.indexOf("Edm.Int") === 0 && typeof id !== "number") {
    return parseInt(id);
}
```
This way we would cover Int16, Int32 and Int64.

Thanks!

**Comment by jvert** [comment]
makes sense!
