### ISSUE TITLE
Update not working?

### ISSUE THREAD

**Issue by gebsl** [Groopit/ra-data-odata-server#15]
Hi,

I've experienced problems with updating data records, as my odata backend always complained it can not find the corresponding key. I've had a look into the id-mapper and it seems the id mapping is only done for creating data records, but not for updating.

Locally, I could resolve the issue by adding the id mapping to the update wrapper like this:

```typescript
  wrapper.update = (resource, params) => {
    const id_name = id_map[resource.toLowerCase()];
    if (id_name) {
      // @ts-expect-error TODO: fix incompatible type
      params.data = rename_from_id(id_name, params.data);
      return dataProvider.update(resource, params).then((result) => {
        return {
          ...result,
          data: rename_to_id(id_name, result.data),
        };
      });
    }
    return dataProvider.update(resource, params);
  };
```

Is this probably something that' still missing in this module?

**Comment by jvert** [comment]
From looking at the code there are a few different things that could go wrong here
- are you trying to change the ID field by doing something like `update("Customers", {id: "foo", data: {id: "blah"}});`
- are you looking at the returned record and expecting CustomerId to be renamed to id?

I'm happy to apply your fix, I just want to make sure I add some corresponding unit tests.

**Comment by gebsl** [comment]
In my data structures I have primary keys that divert from the standard naming "id". So in my case there is a data structure with primary key "Key". However, `params.data` always contains the parameter called `id`, as this is used by react-admin (if I understand the framework correctly).

However, the backend service needs the primary key to be named correctly as otherwise it won't find the corresponding record in the database.

**Comment by jvert** [comment]
normally for update, the `data` structure would contain only the fields that were changing. So it would not contain the `id` . Instead that is explicitly passed separately as the `id` field and used as the key.
```ts
dataProvider.update('posts', {
    id: 123,
    data: { title: "hello, world!" },
    previousData: { title: "previous title" }
})
```

**Comment by gebsl** [comment]
Hm, then maybe the server implementation that I'm using is just not behaving correctly. It should rather use the id that's passed in the URL to identify the data record, instead of extracting the id from the POST body I guess.

If that's the case there is no need to change here and I need to find a fix for my server implementation.

**Comment by jvert** [comment]
Yes, for OData the entity to be operated on is always identified by the resource path. See https://www.odata.org/documentation/odata-version-3-0/url-conventions/
