### ISSUE TITLE
Using with authentication tokens

### ISSUE THREAD

**Issue by 25747** [Groopit/ra-data-odata-server#2]
I have done some basic tests with an internal odata feed, and it worked exactly as described! This was especially exciting for my back end team who will definitely see a reduction in their workload maintaining an API if we can utilize this data provider for new projects. Is there is a built in way to add authentication headers, or other data, to the outgoing odata calls? Is this accomplished with the options callback? Thank you

**Comment by jvert** [comment]
Yes, the options callback is the way to do this. For instance, if you have a `getAccessToken()` method that returns `Promise<string>` you could set up your odata like this and inject the token into your headers.

```
            odataProvider("https://myodataservice.com/odata", () => {
                return getAccessToken()
                    .then((token) => ({
                        headers: {
                            Authorization: "Bearer " + token,
                        },
                    }));
            }).then((provider) => setDataProvider(provider));

```

**Comment by 25747** [comment]
That's perfect, just tested and confirmed it. Thank you!
