### ISSUE TITLE
Compatibility with React-admin 5.* version

### ISSUE THREAD

**Issue by Remco4EF** [Groopit/ra-data-odata-server#20]
React-admin adds PR https://github.com/marmelab/react-admin/pull/9612
 this results in a signature change of the Dataprovider type.
The types https://github.com/marmelab/react-admin/blob/05da7f5423a6c2b939c4d187fcaf208af1b900b4/packages/ra-core/src/types.ts#L89

show that getlist etc should have type 'params: GetListParams & QueryFunctionContext'

**Comment by jvert** [comment]
fixed by #21
