### ISSUE TITLE
Allow Http 201 response code for Create requests

### ISSUE THREAD

**Issue by petecollins73** [Groopit/ra-data-odata-server#3]
Hi,

Great Library! Many thanks for your work.

I'm looking at using the library with a set of .Net OData  Controllers that return a 201 Http response code for created items via the the CreatedODataResult Object.

Could the library Create method allow 201 Http responses to be considered successful in addition to 200 responses?

May be rather than: 

 **if (resp.statusCode !== 200) {**

something like:

**if ([200, 201].indexOf(resp.statusCode) === -1) {**
  
Regards,
Pete.

**Comment by jvert** [comment]
makes sense - I guess to be pedantic it should be `if (resp.statusCode >=300)`

Happy to accept a PR, otherwise it'll probably be a little while until I get to this.

**Comment by petecollins73** [comment]
Thanks,

 I'll have a go at a PR for changing to  if (resp.statusCode >=300)

Pete.

**Comment by jvert** [comment]
fixed in #4
