### ISSUE TITLE
Is this project working with React Admin 4.0.4?

### ISSUE THREAD

**Issue by marcelwokkemarin** [Groopit/ra-data-odata-server#7]
Hi,

Today I tried to use this project with React Admin 4.0.4 but ran into countless errors stating stating

webpack < 5 used to include polyfills for node.js core modules by default.......

This happens when I added this line to my code:
import odataProvider, { OdataDataProvider } from "ra-data-odata-server";

So it seems that at the moment ra-data-odata-server is no longer working with React Admin 4.0.4. Are you planning to provide a fix for this?

**Comment by jvert** [comment]
I took a look at this a few weeks ago but I didn't see any easy fix. A real fix is more involved and I don't think I will have time for that in the near future. So until then I suggest sticking with RA 3.x. Maybe including your own polyfills will allow you to get past this but I didn't try that.

**Comment by marcelwokkemarin** [comment]
Thanks for the quick reply. I saw the polyfill solution on SO, but since the list of errors is long I didn't go along that route. For now I will go back to RA 3.x

**Comment by jvert** [comment]
Just published a new major release 3.0.0 which now works with RA 4.2.x.
